unrelateddata=["Hello",
    "Hi!",
    "How are you doing ?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome.",
    "what is your name ?" ,
    "I'm Edu-Helper Bot",
    "who made you ?",
    "I created by 9331-Vishal Naik, 9332-Devashish Parsekar, 9333-Gopal Parwar,9334-Rahul pereira,9336-Deepak prasad, 9337-Rahulkumar,9338-Sayali Redkar",
    "hello",
    "Hi there, Welcome to Edu-Helper! 👋 If you need any assistance, I'm always here."]